[package]
name = "ide-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-domain = { path = "../ide-domain" }
ide-terminal = { path = "../ide-terminal" }
ide-text = { path = "../ide-text" }
ide-workspace = { path = "../ide-workspace" }
ui-api = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-api" }
ui-components = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-components" }
ui-editor = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-editor" }
ui-core = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-core" }
ui-render-api = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-render-api" }

[lints]
workspace = true
