[package]
name = "ide-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-application = { path = "../ide-application" }
ide-domain = { path = "../ide-domain" }
ide-terminal = { path = "../ide-terminal" }
ide-workspace = { path = "../ide-workspace" }
ui-api.workspace = true
ui-components.workspace = true
ui-editor.workspace = true
ui-core.workspace = true
ui-focus.workspace = true
ui-host.workspace = true
ui-commands.workspace = true
ui-layout-api.workspace = true
ui-layout-taffy.workspace = true
ui-render-api.workspace = true
ui-window-api.workspace = true

[[bench]]
name = "frame"
harness = false

[lints]
workspace = true
