[package]
name = "ide-application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-debug-api = { path = "../ide-debug-api" }
ide-domain = { path = "../ide-domain" }
ide-language-api = { path = "../ide-language-api" }
ide-toolchain-api = { path = "../ide-toolchain-api" }
thiserror.workspace = true

[dev-dependencies]
async-trait.workspace = true

[lints]
workspace = true
