[package]
name = "ide-build-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-project-model = { path = "../ide-project-model" }
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
