[package]
name = "java-javac-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-domain = { path = "../ide-domain" }
ide-process = { path = "../ide-process" }
ide-toolchain-api = { path = "../ide-toolchain-api" }
java-toolchain = { path = "../java-toolchain" }

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
