[package]
name = "ide-process"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-domain = { path = "../ide-domain" }
thiserror.workspace = true
tokio.workspace = true
sysinfo.workspace = true
tracing.workspace = true

[lints]
workspace = true

