[package]
name = "ide-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ide-application = { path = "../ide-application" }
ide-core = { path = "../ide-core" }
ide-debug-api = { path = "../ide-debug-api" }
ide-project = { path = "../ide-project" }
ide-domain = { path = "../ide-domain" }
ide-language-host = { path = "../ide-language-host" }
ide-toolchain-api = { path = "../ide-toolchain-api" }
java-debug-adapter = { path = "../java-debug-adapter" }
java-gradle-adapter = { path = "../java-gradle-adapter" }
java-javac-adapter = { path = "../java-javac-adapter" }
java-maven-adapter = { path = "../java-maven-adapter" }
java-toolchain = { path = "../java-toolchain" }
language-java = { path = "../language-java" }
ide-process = { path = "../ide-process" }
ide-terminal = { path = "../ide-terminal" }
ide-ui = { path = "../ide-ui" }
ide-workspace = { path = "../ide-workspace" }
pollster.workspace = true
rfd.workspace = true
tracing.workspace = true
tokio.workspace = true
ui-clipboard-arboard = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-clipboard-arboard" }
ui-core = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-core" }
ui-render-api = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-render-api" }
ui-render-wgpu = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-render-wgpu" }
ui-text-cosmic = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-text-cosmic" }
ui-window-api = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-window-api" }
ui-window-winit = { path = "C:/Users/jdani/Documents/projetos/rust/ERLibUi/crates/ui-window-winit" }
winit.workspace = true

[lints]
workspace = true
