[package]
name = "ide-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-application = { path = "../ide-application" }
ide-core = { path = "../ide-core" }
ide-debug-api = { path = "../ide-debug-api" }
ide-project = { path = "../ide-project" }
ide-domain = { path = "../ide-domain" }
ide-language-api = { path = "../ide-language-api" }
ide-language-host = { path = "../ide-language-host" }
ide-toolchain-api = { path = "../ide-toolchain-api" }
language-java = { path = "../language-java" }
ide-process = { path = "../ide-process" }
ide-terminal = { path = "../ide-terminal" }
ide-ui = { path = "../ide-ui" }
ide-workspace = { path = "../ide-workspace" }
pollster.workspace = true
rfd.workspace = true
tracing.workspace = true
tokio.workspace = true
ui-clipboard-arboard.workspace = true
ui-core.workspace = true
ui-render-api.workspace = true
ui-render-wgpu.workspace = true
ui-text-cosmic.workspace = true
ui-window-api.workspace = true
ui-window-winit.workspace = true
winit.workspace = true

[lints]
workspace = true
