[package]
name = "java-debug-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-debug-api = { path = "../ide-debug-api" }
ide-domain = { path = "../ide-domain" }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }

[lints]
workspace = true
