[package]
name = "java-gradle-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
ide-process = { path = "../ide-process" }
ide-project = { path = "../ide-project" }

[dev-dependencies]
ide-domain = { path = "../ide-domain" }
tokio.workspace = true

[lints]
workspace = true
